% testIInj.m
%
% Function that generates a current injection protocol for testing purposes. 
% The function creates a linear ramp of current injections over a specified 
% duration, with the option to repeat the ramp multiple times.
%
% INPUTS:
% - settings    : Struct containing electrophysiological setup settings,
%                 typically obtained from the ephysSettings() function.
% - durScans    : Total duration of the current injection protocol in scans.
%
% OUTPUTS:
% - iInjOut     : Output vector containing the current injection values 
%                 generated by the function, structured to match the total 
%                 duration specified by durScans.
% - iInjParams  : Struct for holding parameters related to the current 
%                 injection (currently empty).
%
function [iInjOut, iInjParams] = testIInjFn(settings, durScans)
    outDur = 20000;

    iInjParams = [];
    
    out = (linspace(-2,2,outDur))';

    numRep = floor(durScans / outDur);
    
    remainder = mod(durScans, outDur);
    
    iInjOut = repmat(out,numRep,1);
    
    iInjOut = [iInjOut; out(1:remainder)];
    
end